### PR TITLE
MAKER-556, MAKER-555; Serial fixes for Galileo & Edison

### PR DESCRIPTION
**Pull request by eriknyquist**
Commit messages are sufficiently explanatory.

### CODE REVIEW

**Comment by eriknyquist** [comment]
@SidLeung @calvinatintel @bigdinotech ready for review / verification

**Comment by SidLeung** [comment]
@eriknyquist @bigdinotech @calvinatintel Checked out the changes, looked good.  Ready to merge.  Interesting findings though.  Without understanding the code/structure in depth, would it be more practical to create the thread upon object instantiation and close the thread upon destruction.  No additional calls are needed.

**Comment by eriknyquist** [comment]
@SidLeung yes what you describe is currently what happens.

`Serial.begin()` instantiates the thread object `_thread` by calling `pthread_create`, and sets up a pipe so that the main thread can communicate with `_thread`.

`Serial.end()` then signals `_thread` (who needs to do some cleanup before exiting) by writing to the pipe, and calls `pthread_join` in order to wait for `_thread` to finish cleaning up.

The problem then is with calling `Serial.end()` twice in a row; during the second call, `pthread_join` is being called on thread object `_thread` which was already joined in the first call-- this is explicitly called out in the man page as undefined behaviour (whenever `pthread_join` is used, it is always the responsibility of the caller to ensure that a thread is not joined twice). In this case I guess it was just spinning and waiting for some flag to be set, which would never happen because the thread that's supposed to set it doesn't exist anymore, and the whole thing hangs.

Does that answer your concern? Or did I miss your point :) ?

**Comment by SidLeung** [comment]
@eriknyquist Understood the issue and thanks for the details.  Not a concern I have.  I think I am just pondering upon design preferences, not a proposed change here.  I was just wondering if it would be more practical to make the pthread_create call in the Serial constructor instead of having a standalone method, begin(), to do it.

**Comment by eriknyquist** [comment]
@SidLeung OK I get you now. Yes, using the class constructor and destructor for creating/joining pthreads would be cleaner (and would avoid needing an extra bool), except the user doesn't instantiate those classes (Serial and Serial1), so it would mean that even if a sketch doesn't use Serial those threads will be running anyway. I guess it doesn't break anything, just unnecessary (admittedly, minimal) overhead.

**Comment by eriknyquist** [comment]
@SidLeung what say you? should the pthread handling go into begin/end methods (current), or constructor and destructor? I vote begin/end, for the reason in my last comment.

**Comment by SidLeung** [comment]
I agree with you, @eriknyquist .  I brought up the issue to highlight the importance of shielding the end users from information/configuration that are not necessary for them to understand.  The more info can be shielded away, the easier for the user to utilize, and the more flexibility on our side for future changes.  @calvinatintel Changes are good to go.  Please merge.

**Comment by eriknyquist** [comment]
Rebased my fork on top of the master.

**Pull request closed without merging**
