### PR TITLE
MAKER-548

### PR DESCRIPTION
**Pull request by noelpaz**
Added comments to indicate that the functions mkdir, rmdir and remove return 0 instead of 1 on success and provided explnation due to underlying Linux.

### CODE REVIEW

**Comment by noelpaz** [comment]
@calvinatintel  @bigdinotech  please review

**Comment by bigdinotech** [comment]
@calvinatintel looks good

**Comment by noelpaz** [comment]
@calvinatintel Amended comment. 

"MAKER-548 Added comments to explain return value of some SD functions

Added comments to indicate that mkdir, rmdir and remove return 0 not 1 on success with the explanation of the underlying Linux"

**Comment by calvinatintel** [comment]
Committed after an amend: https://github.com/01org/corelibs-edison/commit/e97e06666059a6b5c988c961aab08bea27386078

**Pull request closed without merging**
